### ISSUE TITLE
各部門最新消息的搬移

### ISSUE THREAD

**Issue by wildskyf** [NTNUSA-info/NTNUSA-site#18]
舊網站我備份在 http://wildsky.cc/NTNUSA
有些連結可能掛了

文章建議以 [Markdown](http://markdown.tw/) 撰寫
不過他跟 html 不衝突，可以混用

**Comment by wi1d5ky** [comment]
Not my business anymore.

**Comment by wildskyf** [comment]
備份已刪除。
