### ISSUE TITLE
slack 補上載點

### ISSUE THREAD

**Issue by wildskyf** [NTNUSA-info/NTNUSA-site#24]
SLACK 介紹頁面補上 Google play 和 App store 載點

**Comment by wildskyf** [comment]
### Google play 載點

https://play.google.com/store/apps/details?id=com.Slack&hl=zh_TW

**Comment by wildskyf** [comment]
### Mac 載點

https://itunes.apple.com/tw/app/slack/id803453959?mt=12

**Comment by wildskyf** [comment]
### App store 載點

https://itunes.apple.com/us/app/slack-team-communication/id618783545?mt=8

**Comment by wi1d5ky** [comment]
Not my business anymore.
